---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV["EC2_SSH_KEY_NAME"] %>
  region: us-west-2
  security_group_ids: ["sg-401e0e25"]
  iam_profile_name: testKitchenAndKnifeEc2
  instance_type: c4.large
  ebs_optimized: true
  tags:
    Name: "bjc_workstation-localdev-kitchen-instance"
    created-by: "test-kitchen"
    user: <%= ENV['USER'] %>
    X-Dept: Sales
    X-Contact: <%= ENV['USER'] %>
    X-Production: "false"

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.3.42

verifier:
  name: inspec

platforms:
  - name: windows-2016
    # driver_config:
      # image_id: ami-48b4bf31

transport:
  ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %>
  
suites:
  - name: default
    run_list:
      # The test cookbook is located in test/fixtures.
      # It is what puts secret keys, certs, etc. in place
      - recipe[test::default]
      - recipe[bjc_workstation::default]
    attributes:
      chocolatey:
        upgrade: true
      demo:
        domain_prefix: ''
        domain: 'automate-demo.com'
        enterprise: 'automate-demo'
        org: 'automate'
        hosts:
        workstations: 1
        workstation-number: 1
        versions:
          chefdk: 'stable-2.1.11'
    verifier:
      inspec_tests:
        - test/integration/default
