---
driver:
  name: azurerm

driver_config:
  subscription_id: <%= ENV["AZURE_SUBSCRIPTION_ID"] %>
  location: 'West US'
  machine_size: 'Standard_DS3_v2'

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.3.42

verifier:
  name: inspec

platforms:
  - name: windows-2016
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
      os_type: windows

suites:
  - name: default
    run_list:
      # The test cookbook is located in test/fixtures.
      # It is what puts secret keys, certs, etc. in place
      - recipe[test::default]
      - recipe[bjc_workstation::default]
    attributes:
      chocolatey:
        upgrade: true
      demo:
        domain_prefix: ''
        domain: 'automate-demo.com'
        enterprise: 'automate-demo'
        org: 'automate'
        hosts:
        workstations: 1
        workstation-number: 1
        versions:
          chefdk: 'stable-2.1.11'
    verifier:
      inspec_tests:
        - test/integration/default
